# Generated by Django 4.0.3 on 2022-03-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name ')),
                ('address', models.CharField(max_length=120, verbose_name='Venue Address ')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Venue zipcode ')),
                ('phone', models.CharField(max_length=13, verbose_name='Venue Number ')),
                ('web', models.URLField(verbose_name='Website Address ')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Venue Email')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date ')),
                ('manager', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('event_hours', models.IntegerField()),
                ('attendees', models.ManyToManyField(to='events.myclubuser')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
        ),
    ]
