# Generated by Django 4.0.3 on 2022-07-01 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_alter_event_attendees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyClubUser',
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(null=True, related_name='all_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
