# Generated by Django 4.0.3 on 2022-07-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_delete_myclubuser_alter_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_hours',
        ),
    ]
