# Generated by Django 4.0.3 on 2022-07-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approced'),
        ),
    ]
